/**
 * Comprehensive Indian States and Major Exam Hub Cities
 * 100% Offline-first location dataset for student profiling, leaderboards, and state rankings.
 */

export const INDIA_STATES_AND_CITIES: Record<string, string[]> = {
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Rewa',
    'Satna',
    'Ratlam',
    'Dewas',
    'Chhindwara',
    'Shivpuri',
    'Vidisha',
    'Mandsaur',
    'Khargone',
    'Neemuch',
    'Khandwa',
    'Hoshangabad (Narmadapuram)',
    'Sehore',
    'Betul',
    'Datia',
    'Damoh',
    'Morena',
    'Bhind',
    'Singrauli',
    'Katni',
    'Seoni',
    'Balaghat',
    'Guna',
    'Panna',
    'Chhatarpur',
    'Tikamgarh',
    'Raisen',
    'Rajgarh',
    'Shajapur',
    'Barwani',
    'Dhar',
    'Alirajpur',
    'Jhabua',
    'Harda',
    'Sheopur',
    'Ashoknagar',
    'Burhanpur',
    'Anuppur',
    'Umaria',
    'Dindori',
    'Mandla',
    'Shahdol',
    'Narsinghpur',
    'Sidhi',
    'Niwari',
    'Maihar',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Varanasi',
    'Prayagraj (Allahabad)',
    'Noida',
    'Greater Noida',
    'Ghaziabad',
    'Agra',
    'Meerut',
    'Aligarh',
    'Bareilly',
    'Moradabad',
    'Gorakhpur',
    'Jhansi',
    'Mathura',
    'Ayodhya (Faizabad)',
    'Saharanpur',
    'Muzaffarnagar',
    'Firozabad',
    'Budaun',
    'Rampur',
    'Shahjahanpur',
    'Farrukhabad',
    'Hapur',
    'Etawah',
    'Mirzapur',
    'Bulandshahr',
    'Sambhal',
    'Amroha',
    'Hardoi',
    'Fatehpur',
    'Raebareli',
    'Orai',
    'Sitapur',
    'Bahraich',
    'Modinagar',
    'Unnao',
    'Jaunpur',
    'Lakhimpur',
    'Hathras',
    'Banda',
    'Pilibhit',
    'Barabanki',
    'Mughalsarai',
    'Gonda',
    'Mainpuri',
    'Lalitpur',
    'Etah',
    'Deoria',
    'Ghazipur',
    'Sultanpur',
    'Azamgarh',
    'Bijnor',
    'Basti',
    'Chandauli',
    'Ballia',
    'Akbarpur',
  ],
  'Rajasthan': [
    'Jaipur',
    'Kota',
    'Jodhpur',
    'Udaipur',
    'Bikaner',
    'Ajmer',
    'Bhilwara',
    'Alwar',
    'Sikar',
    'Bharatpur',
    'Sri Ganganagar',
    'Pali',
    'Chittorgarh',
    'Tonk',
    'Kishangarh',
    'Beawar',
    'Hanumangarh',
    'Dhaulpur',
    'Gangapur City',
    'Sawai Madhopur',
    'Churu',
    'Jhunjhunu',
    'Baran',
    'Hindaun',
    'Nagaur',
    'Makrana',
    'Sujangarh',
    'Bhiwadi',
    'Jalore',
    'Banswara',
    'Dausa',
    'Barmer',
    'Jaisalmer',
    'Rajsamand',
  ],
  'Bihar': [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Darbhanga',
    'Purnia',
    'Bihar Sharif',
    'Arrah (Bhojpur)',
    'Begusarai',
    'Katihar',
    'Munger',
    'Chhapra',
    'Sasaram',
    'Hajipur',
    'Dehri',
    'Siwan',
    'Bettiah',
    'Motihari',
    'Bagaha',
    'Kishanganj',
    'Jamalpur',
    'Buxar',
    'Jehanabad',
    'Aurangabad',
    'Lakhisarai',
    'Nawada',
    'Samastipur',
    'Madhubani',
    'Sitamarhi',
    'Gopalganj',
    'Saharsa',
    'Supaul',
  ],
  'Delhi (NCT)': [
    'New Delhi',
    'Central Delhi',
    'North Delhi',
    'South Delhi',
    'East Delhi',
    'West Delhi',
    'North East Delhi',
    'North West Delhi',
    'South East Delhi',
    'South West Delhi',
    'Dwarka',
    'Rohini',
    'Connaught Place',
    'Karol Bagh',
    'Mukherjee Nagar',
    'Rajendra Nagar',
    'Laxmi Nagar',
    'Kalu Sarai',
    'Janakpuri',
    'Pitampura',
  ],
  'Maharashtra': [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Nashik',
    'Thane',
    'Chhatrapati Sambhaji Nagar (Aurangabad)',
    'Solapur',
    'Amravati',
    'Kolhapur',
    'Navi Mumbai',
    'Nanded',
    'Jalgaon',
    'Akola',
    'Latur',
    'Dhule',
    'Ahmednagar',
    'Chandrapur',
    'Parbhani',
    'Ichalkaranji',
    'Jalna',
    'Bhusawal',
    'Panvel',
    'Satara',
    'Beed',
    'Yavatmal',
    'Gondia',
    'Wardha',
    'Barshi',
    'Achalpur',
    'Osmanabad',
    'Nandurbar',
    'Ratnagiri',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Gandhinagar',
    'Junagadh',
    'Gandhidham',
    'Anand',
    'Navsari',
    'Morbi',
    'Nadiad',
    'Surendranagar',
    'Bharuch',
    'Mehsana',
    'Bhuj',
    'Porbandar',
    'Palanpur',
    'Valsad',
    'Vapi',
    'Gondal',
    'Veraval',
    'Godhra',
    'Patan',
    'Kalol',
    'Dahod',
    'Botad',
    'Amreli',
    'Deesa',
    'Jetpur',
  ],
  'Chhattisgarh': [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Durg',
    'Rajnandgaon',
    'Jagdalpur',
    'Raigarh',
    'Ambikapur',
    'Dhamtari',
    'Mahasamund',
    'Kanker',
    'Kawardha',
    'Champa',
    'Bhatapara',
    'Dalli-Rajhara',
    'Naila Janjgir',
    'Tilda Newra',
    'Mungeli',
    'Bemetara',
  ],
  'Haryana': [
    'Gurugram (Gurgaon)',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
    'Hisar',
    'Karnal',
    'Sonipat',
    'Panchkula',
    'Sirsa',
    'Bhiwani',
    'Bahadurgarh',
    'Jind',
    'Thanesar (Kurukshetra)',
    'Kaithal',
    'Rewari',
    'Palwal',
    'Hansi',
    'Narnaul',
    'Fatehabad',
  ],
  'Punjab': [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali (SAS Nagar)',
    'Hoshiarpur',
    'Batala',
    'Pathankot',
    'Moga',
    'Abohar',
    'Malerkotla',
    'Khanna',
    'Muktsar',
    'Barnala',
    'Firozpur',
    'Kapurthala',
    'Phagwara',
    'Zirakpur',
    'Sangrur',
  ],
  'Uttarakhand': [
    'Dehradun',
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rudrapur',
    'Kashipur',
    'Rishikesh',
    'Kotdwar',
    'Pithoragarh',
    'Manglaur',
    'Nainital',
    'Almora',
    'Mussoorie',
    'Tehri',
    'Pauri',
    'Ramnagar',
    'Kichha',
  ],
  'Jharkhand': [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro Steel City',
    'Deoghar',
    'Phusro',
    'Hazaribagh',
    'Giridih',
    'Ramgarh',
    'Medininagar (Daltonganj)',
    'Chirkunda',
    'Jhumri Telaiya',
    'Sahibganj',
    'Chaibasa',
    'Dumka',
    'Gumia',
    'Madhupur',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Asansol',
    'Siliguri',
    'Durgapur',
    'Bardhaman',
    'Malda',
    'Baharampur',
    'Habra',
    'Kharagpur',
    'Shantipur',
    'Dankuni',
    'Dhulian',
    'Ranaghat',
    'Haldia',
    'Raiganj',
    'Krishnanagar',
    'Nabadwip',
    'Midnapore',
    'Jalpaiguri',
    'Balurghat',
    'Basirhat',
    'Bankura',
    'Darjeeling',
    'Purulia',
  ],
  'Odisha': [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Balasore',
    'Bhadrak',
    'Baripada',
    'Jharsuguda',
    'Jeypore',
    'Bargarh',
    'Rayagada',
    'Bolangir',
    'Angul',
    'Dhenkanal',
  ],
  'Assam': [
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
    'Bongaigaon',
    'Dhubri',
    'Diphu',
    'North Lakhimpur',
    'Karimganj',
    'Sivasagar',
    'Goalpara',
    'Barpeta',
  ],
  'Telangana': [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Khammam',
    'Karimnagar',
    'Ramagundam',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Suryapet',
    'Miryalaguda',
    'Siddipet',
    'Jagtial',
    'Mancherial',
  ],
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Kakinada',
    'Rajahmundry',
    'Kadapa',
    'Tirupati',
    'Anantapur',
    'Vizianagaram',
    'Eluru',
    'Ongole',
    'Nandyal',
    'Machilipatnam',
    'Adoni',
    'Tenali',
    'Proddatur',
    'Chittoor',
    'Hindupur',
    'Bhimavaram',
  ],
  'Karnataka': [
    'Bengaluru (Bangalore)',
    'Mysuru (Mysore)',
    'Hubballi-Dharwad',
    'Mangaluru (Mangalore)',
    'Belagavi (Belgaum)',
    'Kalaburagi (Gulbarga)',
    'Davanagere',
    'Ballari (Bellary)',
    'Vijayapura (Bijapur)',
    'Shivamogga (Shimoga)',
    'Tumakuru (Tumkur)',
    'Raichur',
    'Bidar',
    'Hosapete',
    'Gadag-Betageri',
    'Robertsonpet',
    'Hassan',
    'Bhadravati',
    'Chitradurga',
    'Udupi',
    'Kolar',
    'Mandya',
    'Chikkamagaluru',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli (Trichy)',
    'Salem',
    'Tirunelveli',
    'Tiruppur',
    'Ranipet',
    'Nagercoil',
    'Thanjavur',
    'Vellore',
    'Kancheepuram',
    'Erode',
    'Tiruvannamalai',
    'Pollachi',
    'Rajapalayam',
    'Sivakasi',
    'Pudukkottai',
    'Neyveli',
    'Nagapattinam',
    'Viluppuram',
    'Dindigul',
    'Kumbakonam',
    'Cuddalore',
    'Hosur',
    'Ambur',
    'Karaikkudi',
  ],
  'Kerala': [
    'Thiruvananthapuram',
    'Kochi (Cochin)',
    'Kozhikode (Calicut)',
    'Kollam',
    'Thrissur',
    'Kannur',
    'Alappuzha',
    'Kottayam',
    'Palakkad',
    'Manjeri',
    'Thalassery',
    'Ponnani',
    'Vatakara',
    'Kanhangad',
    'Payyanur',
    'Koyilandy',
    'Neyyattinkara',
    'Kayamkulam',
    'Nedumangad',
    'Malappuram',
  ],
  'Jammu & Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Udhampur',
    'Sopore',
    'Kathua',
    'Bandipore',
    'Pulwama',
    'Rajouri',
    'Poonch',
    'Kupwara',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Dharamshala',
    'Solan',
    'Mandi',
    'Palampur',
    'Baddi',
    'Nahan',
    'Paonta Sahib',
    'Sundernagar',
    'Kullu',
    'Hamirpur',
    'Bilaspur',
    'Una',
    'Chamba',
  ],
  'Goa': [
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
    'Bicholim',
    'Curchorem',
    'Cuncolim',
  ],
  'Chandigarh': [
    'Chandigarh City',
    'Sector 17',
    'Sector 34 (Coaching Hub)',
    'Manimajra',
  ],
  'Puducherry': [
    'Puducherry City',
    'Karaikal',
    'Yanam',
    'Mahe',
  ],
  'Tripura': [
    'Agartala',
    'Dharmanagar',
    'Udaipur',
    'Kailasahar',
    'Belonia',
  ],
  'Meghalaya': [
    'Shillong',
    'Tura',
    'Jowai',
    'Nongpoh',
  ],
  'Manipur': [
    'Imphal',
    'Thoubal',
    'Bishnupur',
    'Churachandpur',
  ],
  'Nagaland': [
    'Kohima',
    'Dimapur',
    'Mokokchung',
    'Tuensang',
  ],
  'Mizoram': [
    'Aizawl',
    'Lunglei',
    'Champhai',
    'Serchhip',
  ],
  'Arunachal Pradesh': [
    'Itanagar',
    'Naharlagun',
    'Pasighat',
    'Tawang',
    'Ziro',
  ],
  'Sikkim': [
    'Gangtok',
    'Namchi',
    'Geyzing',
    'Mangan',
  ],
  'Ladakh': [
    'Leh',
    'Kargil',
  ],
};

/**
 * Returns all Indian states and Union Territories in alphabetical order
 */
export function getAllIndianStates(): string[] {
  return Object.keys(INDIA_STATES_AND_CITIES);
}

/**
 * Returns cities for a given state name (fuzzy match supported)
 */
export function getCitiesForState(stateName: string): string[] {
  if (!stateName) return INDIA_STATES_AND_CITIES['Madhya Pradesh'];

  const foundKey = Object.keys(INDIA_STATES_AND_CITIES).find(
    (k) => k.toLowerCase() === stateName.toLowerCase() || k.toLowerCase().includes(stateName.toLowerCase())
  );

  return foundKey ? INDIA_STATES_AND_CITIES[foundKey] : ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior'];
}

/**
 * Search cities with optional state scoping
 */
export function searchCities(query: string, stateName?: string): string[] {
  const q = (query || '').toLowerCase().trim();
  const pool = stateName ? getCitiesForState(stateName) : Object.values(INDIA_STATES_AND_CITIES).flat();
  if (!q) return pool.slice(0, 30);
  return pool.filter((city) => city.toLowerCase().includes(q));
}

/**
 * Live network fetcher with instant fallback to offline database
 */
export async function fetchLiveCitiesForState(stateName: string): Promise<string[]> {
  try {
    const res = await fetch('https://countriesnow.space/api/v0.1/countries/state/cities', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ country: 'India', state: stateName }),
    });
    const json = await res.json();
    if (json && !json.error && Array.isArray(json.data) && json.data.length > 0) {
      return json.data;
    }
  } catch (err) {
    // Offline / timeout: fallback seamlessly to local dataset
  }
  return getCitiesForState(stateName);
}
