-- ==============================================================================
-- ZENZA COMPLETE SUPABASE MASTER DATABASE SETUP
-- Run this entire script in your Supabase SQL Editor (http://35.234.211.3:8000)
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. CORE TABLES

-- Businesses (Coachings, Schools, Colleges, Libraries, Hostels)
CREATE TABLE IF NOT EXISTS public.businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    admin_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    business_name TEXT NOT NULL,
    business_type TEXT NOT NULL,
    organization_id TEXT UNIQUE NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Profiles (Users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT,
    role TEXT CHECK (role IN ('student', 'admin', 'staff')),
    business_id UUID REFERENCES public.businesses(id) ON DELETE SET NULL,
    claimed BOOLEAN DEFAULT false,
    avatar_url TEXT,
    is_external BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure avatar_url and is_external exist if profiles already created
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_external BOOLEAN DEFAULT false;

-- Batches / Shifts / Rooms
CREATE TABLE IF NOT EXISTS public.batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Students / Members
CREATE TABLE IF NOT EXISTS public.students (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    enrollment_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    father_name TEXT,
    phone TEXT,
    parent_name TEXT,
    parent_phone TEXT,
    email TEXT,
    address TEXT,
    batch_name TEXT NOT NULL,
    course TEXT,
    valid_from TEXT,
    valid_till TEXT,
    dob TEXT,
    fee_amount NUMERIC NOT NULL DEFAULT 0,
    fee_cycle TEXT DEFAULT 'monthly' CHECK (fee_cycle IN ('monthly', 'yearly', 'one time')),
    fee_due_date TEXT DEFAULT '15',
    fee_status TEXT DEFAULT 'unpaid' CHECK (fee_status IN ('paid', 'unpaid', 'overdue')),
    next_due_date DATE DEFAULT (CURRENT_DATE + INTERVAL '1 month'),
    admission_date DATE DEFAULT CURRENT_DATE,
    photo_url TEXT,
    whatsapp TEXT,
    blood_group TEXT,
    duration TEXT DEFAULT '1 Year',
    batch_timing TEXT DEFAULT '10:00 AM - 01:00 PM',
    aadhaar_number TEXT,
    secret_code TEXT,
    whatsapp_number TEXT,
    device_id TEXT,
    is_claimed BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, business_id)
);

-- Attendance
CREATE TABLE IF NOT EXISTS public.attendance (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT CHECK (status IN ('present', 'absent', 'late')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(student_id, date)
);

-- Payments / Fees
CREATE TABLE IF NOT EXISTS public.payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_mode TEXT CHECK (payment_mode IN ('cash', 'online', 'cheque', 'upi')),
    receipt_no TEXT,
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Community Posts
CREATE TABLE IF NOT EXISTS public.community_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    author_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    author_role TEXT NOT NULL,
    author_avatar TEXT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT DEFAULT 'General',
    image_url TEXT,
    attachments JSONB DEFAULT '[]'::jsonb,
    likes_count INT DEFAULT 0,
    liked_by JSONB DEFAULT '[]'::jsonb,
    comments_count INT DEFAULT 0,
    is_pinned BOOLEAN DEFAULT false,
    is_edited BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tests & Test Banks
CREATE TABLE IF NOT EXISTS public.test_banks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    duration_minutes INT NOT NULL DEFAULT 60,
    total_marks NUMERIC NOT NULL DEFAULT 100,
    passing_marks NUMERIC NOT NULL DEFAULT 40,
    batch_names TEXT[] DEFAULT '{}',
    is_public BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'completed')),
    scheduled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.test_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id UUID REFERENCES public.tests(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    question_image_url TEXT,
    options JSONB NOT NULL,
    correct_option INT NOT NULL,
    marks NUMERIC NOT NULL DEFAULT 1,
    negative_marks NUMERIC NOT NULL DEFAULT 0,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.test_submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id UUID REFERENCES public.tests(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
    answers JSONB NOT NULL DEFAULT '{}'::jsonb,
    score NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'submitted' CHECK (status IN ('in_progress', 'submitted', 'evaluated')),
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(test_id, student_id)
);

-- Study Materials
CREATE TABLE IF NOT EXISTS public.study_materials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    file_url TEXT NOT NULL,
    file_type TEXT,
    file_size BIGINT,
    batch_names TEXT[] DEFAULT '{}',
    uploaded_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Alerts & Notifications
CREATE TABLE IF NOT EXISTS public.alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'general',
    target_batches TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;


-- Students
CREATE POLICY "Admins can manage students in their business" ON public.students FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Students can view and claim their record" ON public.students FOR SELECT USING (
    auth.uid() = user_id OR user_id IS NULL
);
CREATE POLICY "Students can claim unclaimed record" ON public.students FOR UPDATE USING (
    user_id IS NULL OR auth.uid() = user_id
) WITH CHECK (
    auth.uid() = user_id
);


-- Batches
CREATE POLICY "Admins can manage batches" ON public.batches FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Anyone can view batches" ON public.batches FOR SELECT USING (true);

-- Attendance
CREATE POLICY "Admins can manage attendance" ON public.attendance FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Students can view their attendance" ON public.attendance FOR SELECT USING (
    student_id IN (SELECT id FROM public.students WHERE user_id = auth.uid())
);

-- Payments
CREATE POLICY "Admins can manage payments" ON public.payments FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Students can view their payments" ON public.payments FOR SELECT USING (
    student_id IN (SELECT id FROM public.students WHERE user_id = auth.uid())
);

-- Community Posts
CREATE POLICY "Admins can manage posts" ON public.community_posts FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Students can view posts" ON public.community_posts FOR SELECT USING (
    business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid())
);

-- Tests
CREATE POLICY "Admins manage tests" ON public.tests FOR ALL USING (business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid()));
CREATE POLICY "Students view tests" ON public.tests FOR SELECT USING (business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid()));

CREATE POLICY "Admins manage test questions" ON public.test_questions FOR ALL USING (
    test_id IN (SELECT id FROM public.tests WHERE business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid()))
);
CREATE POLICY "Students view test questions" ON public.test_questions FOR SELECT USING (
    test_id IN (SELECT id FROM public.tests WHERE business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid()))
);

CREATE POLICY "Admins view submissions" ON public.test_submissions FOR SELECT USING (
    test_id IN (SELECT id FROM public.tests WHERE business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid()))
);
CREATE POLICY "Students insert submissions" ON public.test_submissions FOR INSERT WITH CHECK (
    student_id IN (SELECT id FROM public.students WHERE user_id = auth.uid())
);
CREATE POLICY "Students view own submissions" ON public.test_submissions FOR SELECT USING (
    student_id IN (SELECT id FROM public.students WHERE user_id = auth.uid())
);

-- Alerts
CREATE POLICY "Admins manage alerts" ON public.alerts FOR ALL USING (business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid()));
CREATE POLICY "Students view alerts" ON public.alerts FOR SELECT USING (business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid()));

-- 4. HANDLE NEW USER TRIGGER
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  existing_student_id UUID;
  user_role TEXT;
BEGIN
  user_role := new.raw_user_meta_data->>'role';

  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', 'Student User'),
    new.email,
    user_role
  )
  ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name,
      email = EXCLUDED.email,
      role = COALESCE(profiles.role, EXCLUDED.role);

  IF user_role IS NULL OR user_role = 'student' THEN
    SELECT id INTO existing_student_id FROM public.students WHERE email = new.email LIMIT 1;
    IF existing_student_id IS NOT NULL THEN
      UPDATE public.students SET user_id = new.id WHERE id = existing_student_id;
      UPDATE public.profiles SET role = 'student' WHERE id = new.id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. STORAGE BUCKETS & POLICIES
INSERT INTO storage.buckets (id, name, public)
VALUES 
    ('avatars', 'avatars', true),
    ('test-images', 'test-images', true),
    ('study-materials', 'study-materials', true),
    ('attachments', 'attachments', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Storage Public All" ON storage.objects;
CREATE POLICY "Storage Public All" ON storage.objects FOR ALL USING (true) WITH CHECK (true);

-- 6. PERMISSIONS & ROLE GRANTS
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO postgres, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO postgres, anon, authenticated, service_role;

-- 7. TARGET EXAMS & SUB EXAMS
CREATE TABLE IF NOT EXISTS public.exams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'Competitive Exam',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sub_exams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    exam_id UUID REFERENCES public.exams(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    syllabus_summary TEXT,
    total_marks NUMERIC DEFAULT 100,
    duration_minutes INTEGER DEFAULT 60,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sub_exams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Exams are viewable by all authenticated users" ON public.exams;
CREATE POLICY "Exams are viewable by all authenticated users" ON public.exams FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage exams" ON public.exams;
CREATE POLICY "Admins can manage exams" ON public.exams FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Sub-exams are viewable by all authenticated users" ON public.sub_exams;
CREATE POLICY "Sub-exams are viewable by all authenticated users" ON public.sub_exams FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage sub-exams" ON public.sub_exams;
CREATE POLICY "Admins can manage sub-exams" ON public.sub_exams FOR ALL USING (true) WITH CHECK (true);



