-- 1. PROFILES TABLE (Stores roles and basic user details)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  name TEXT,
  role TEXT DEFAULT 'student' CHECK (role IN ('admin', 'student')),
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Allow public read of profiles, and update of own profile
CREATE POLICY "Allow public read of profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow users to update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. BATCHES TABLE
CREATE TABLE public.batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read of batches" ON public.batches FOR SELECT USING (true);
CREATE POLICY "Allow admin to insert batches" ON public.batches FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Insert default batches
INSERT INTO public.batches (name) VALUES 
('MPPSC'), ('SSC'), ('VYAPAM'), ('Railway'), ('Banking'), ('UPSC') 
ON CONFLICT (name) DO NOTHING;

-- 3. STUDENTS TABLE (Stores detailed profile data)
CREATE TABLE public.students (
  id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  enrollment_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  father_name TEXT,
  phone TEXT,
  parent_name TEXT,
  parent_phone TEXT,
  email TEXT,
  address TEXT,
  batch_name TEXT NOT NULL, -- e.g. "MPPSC"
  course TEXT,
  valid_from TEXT,
  valid_till TEXT,
  dob TEXT,
  fee_amount NUMERIC NOT NULL DEFAULT 2500,
  fee_status TEXT DEFAULT 'unpaid' CHECK (fee_status IN ('paid', 'unpaid', 'overdue')),
  next_due_date DATE DEFAULT (CURRENT_DATE + INTERVAL '1 month'),
  admission_date DATE DEFAULT CURRENT_DATE,
  photo_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read of students" ON public.students FOR SELECT USING (true);
CREATE POLICY "Allow users to update own student record" ON public.students FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Allow admin to manage students" ON public.students FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 4. ATTENDANCE TABLE
CREATE TABLE public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  date DATE DEFAULT CURRENT_DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('present', 'absent', 'holiday')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (student_id, date)
);

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to read own attendance" ON public.attendance FOR SELECT USING (
  auth.uid() = student_id OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Allow admin to manage attendance" ON public.attendance FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 5. PAYMENTS TABLE (Fee history)
CREATE TABLE public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  month TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'paid' CHECK (status IN ('paid', 'unpaid', 'overdue')),
  paid_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  receipt_no TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to read own payments" ON public.payments FOR SELECT USING (
  auth.uid() = student_id OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Allow admin to manage payments" ON public.payments FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 6. COMMUNITY POSTS TABLE
CREATE TABLE public.community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_name TEXT NOT NULL DEFAULT 'Upendra Sir',
  category TEXT NOT NULL CHECK (category IN ('announcement', 'note', 'schedule')),
  text TEXT NOT NULL,
  likes INT DEFAULT 0,
  comments JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read of community posts" ON public.community_posts FOR SELECT USING (true);
CREATE POLICY "Allow admin to manage community posts" ON public.community_posts FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 7. TRIGGER: AUTOMATIC PROFILE CREATION ON AUTH USER SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', 'Student User'),
    new.email,
    COALESCE(new.raw_user_meta_data->>'role', 'student')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
