-- SQL Patch to restore missing tables: claim_requests and account_deletion_requests
-- Run this script in your Supabase Dashboard SQL Editor (https://supabase.com/dashboard)

-- ===================================================
-- 1. CREATE CLAIM REQUESTS TABLE (FOR AADHAAR/SECRET CLAIMS)
-- ===================================================
DROP TABLE IF EXISTS public.claim_requests CASCADE;

CREATE TABLE public.claim_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'declined')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.claim_requests ENABLE ROW LEVEL SECURITY;

-- Policies for claim_requests
CREATE POLICY "Allow public insert of claim requests" ON public.claim_requests 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to read own requests" ON public.claim_requests 
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow admins to manage requests" ON public.claim_requests 
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.businesses b 
      JOIN public.students s ON s.business_id = b.id 
      WHERE s.id = claim_requests.student_id AND b.admin_id = auth.uid()
    )
  );

-- ===================================================
-- 2. CREATE ACCOUNT DELETION REQUESTS TABLE
-- ===================================================
DROP TABLE IF EXISTS public.account_deletion_requests CASCADE;

CREATE TABLE public.account_deletion_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  user_name TEXT NOT NULL,
  user_email TEXT NOT NULL,
  requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'recovered', 'rejected')),
  scheduled_delete_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.account_deletion_requests ENABLE ROW LEVEL SECURITY;

-- Policies for account_deletion_requests
CREATE POLICY "Allow users to manage own deletion request" ON public.account_deletion_requests
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow admin to manage deletion requests" ON public.account_deletion_requests
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );
