-- SQL Script to drop and recreate community_posts table with the correct V3 fields and types
-- Run this in your Supabase Dashboard SQL Editor (https://supabase.com/dashboard)

DROP TABLE IF EXISTS public.community_posts CASCADE;

CREATE TABLE public.community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
  author_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL DEFAULT 'Admin',
  author_role TEXT DEFAULT 'admin',
  category TEXT NOT NULL CHECK (category IN ('announcement', 'note', 'schedule')),
  text TEXT NOT NULL,
  media_url TEXT,
  file_url TEXT,
  file_name TEXT,
  likes INTEGER DEFAULT 0,
  comments JSONB DEFAULT '[]'::jsonb,
  liked_by JSONB DEFAULT '[]'::jsonb,
  viewed_by JSONB DEFAULT '[]'::jsonb,
  target_batches JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

-- 1. Admins can manage posts of their business
DROP POLICY IF EXISTS "Admins can manage posts" ON public.community_posts;
CREATE POLICY "Admins can manage posts" ON public.community_posts
  FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
  );

-- 2. Students can view posts of their business
DROP POLICY IF EXISTS "Students can view posts" ON public.community_posts;
CREATE POLICY "Students can view posts" ON public.community_posts
  FOR SELECT USING (
    business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid())
  );

-- 3. Authenticated users (students and admins) can update posts (needed to update likes, comments, and viewed_by)
DROP POLICY IF EXISTS "Allow authenticated users to update community posts" ON public.community_posts;
CREATE POLICY "Allow authenticated users to update community posts" ON public.community_posts
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);
