-- Supabase Master Schema (V3)
-- Replaces institutes and coachings with "businesses"

-- 1. CLEANUP (WIPE EVERYTHING)
DROP TABLE IF EXISTS public.claim_requests CASCADE;
DROP TABLE IF EXISTS public.account_deletion_requests CASCADE;
DROP TABLE IF EXISTS public.test_submissions CASCADE;
DROP TABLE IF EXISTS public.test_questions CASCADE;
DROP TABLE IF EXISTS public.test_results CASCADE;
DROP TABLE IF EXISTS public.tests CASCADE;
DROP TABLE IF EXISTS public.test_banks CASCADE;
DROP TABLE IF EXISTS public.community_posts CASCADE;
DROP TABLE IF EXISTS public.payments CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.students CASCADE;
DROP TABLE IF EXISTS public.batches CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.coachings CASCADE;
DROP TABLE IF EXISTS public.institutes CASCADE;
DROP TABLE IF EXISTS public.alerts CASCADE;

-- 2. CREATE CORE TABLES

-- Businesses (Umbrella for Coachings, Schools, Colleges, Libraries, Hostels)
CREATE TABLE public.businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    admin_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    business_name TEXT NOT NULL,
    business_type TEXT NOT NULL, -- e.g. 'Coaching', 'Library', 'School', 'College', 'Hostel'
    organization_id TEXT UNIQUE NOT NULL, -- Format: 3 letters + 4 random (e.g. ALP-X7B2)
    metadata JSONB DEFAULT '{}'::jsonb, -- dynamic parameters based on business type
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Profiles (Users)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT,
    role TEXT CHECK (role IN ('student', 'admin', 'staff')),
    business_id UUID REFERENCES public.businesses(id) ON DELETE SET NULL,
    claimed BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Batches / Shifts / Rooms
CREATE TABLE public.batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
  name TEXT NOT NULL, -- E.g. "MPPSC Batch", "Morning Shift", "Room 101"
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Students / Members
CREATE TABLE public.students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  enrollment_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  father_name TEXT,
  phone TEXT,
  parent_name TEXT,
  parent_phone TEXT,
  email TEXT,
  address TEXT,
  batch_name TEXT NOT NULL, -- Relates to batches/shifts/rooms
  course TEXT,
  valid_from TEXT,
  valid_till TEXT,
  dob TEXT,
  fee_amount NUMERIC NOT NULL DEFAULT 0,
  fee_status TEXT DEFAULT 'unpaid' CHECK (fee_status IN ('paid', 'unpaid', 'overdue')),
  next_due_date DATE DEFAULT (CURRENT_DATE + INTERVAL '1 month'),
  admission_date DATE DEFAULT CURRENT_DATE,
  photo_url TEXT,
  whatsapp TEXT,
  blood_group TEXT,
  duration TEXT DEFAULT '1 Year',
  batch_timing TEXT DEFAULT '10:00 AM - 01:00 PM',
  aadhaar_number TEXT UNIQUE,
  secret_code TEXT UNIQUE,
  whatsapp_number TEXT,
  device_id TEXT,
  is_claimed BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, business_id)
);

-- Attendance
CREATE TABLE public.attendance (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT CHECK (status IN ('present', 'absent', 'late')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(student_id, date)
);

-- Payments
CREATE TABLE public.payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  status TEXT CHECK (status IN ('success', 'failed', 'pending')),
  transaction_id TEXT,
  payment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Community Posts
CREATE TABLE public.community_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
  author_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  author_role TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tests
CREATE TABLE public.tests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  duration_minutes INTEGER NOT NULL,
  total_marks INTEGER NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'completed')),
  batch_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.test_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  test_id UUID REFERENCES public.tests(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL,
  correct_option INTEGER NOT NULL,
  marks INTEGER DEFAULT 1,
  negative_marks NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.test_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  test_id UUID REFERENCES public.tests(id) ON DELETE CASCADE,
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
  answers JSONB NOT NULL,
  score NUMERIC NOT NULL,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(test_id, student_id)
);

CREATE TABLE public.alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    target_role TEXT DEFAULT 'all',
    target_batch TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ENABLE RLS & CREATE POLICIES
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- Businesses
CREATE POLICY "Admins can manage their business" ON public.businesses FOR ALL USING (auth.uid() = admin_id);
CREATE POLICY "Anyone can view businesses" ON public.businesses FOR SELECT USING (true);

-- Profiles
CREATE POLICY "Users can manage own profile" ON public.profiles FOR ALL USING (auth.uid() = id);

-- Students
CREATE POLICY "Admins can manage students in their business" ON public.students FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Students can view their own record" ON public.students FOR SELECT USING (auth.uid() = user_id);

-- Batches
CREATE POLICY "Admins can manage batches" ON public.batches FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Anyone can view batches" ON public.batches FOR SELECT USING (true);

-- Attendance
CREATE POLICY "Admins can manage attendance" ON public.attendance FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Students can view their attendance" ON public.attendance FOR SELECT USING (
    student_id IN (SELECT id FROM public.students WHERE user_id = auth.uid())
);

-- Payments
CREATE POLICY "Admins can manage payments" ON public.payments FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Students can view their payments" ON public.payments FOR SELECT USING (
    student_id IN (SELECT id FROM public.students WHERE user_id = auth.uid())
);

-- Community Posts
CREATE POLICY "Admins can manage posts" ON public.community_posts FOR ALL USING (
    business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid())
);
CREATE POLICY "Students can view posts" ON public.community_posts FOR SELECT USING (
    business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid())
);

-- Tests
CREATE POLICY "Admins manage tests" ON public.tests FOR ALL USING (business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid()));
CREATE POLICY "Students view tests" ON public.tests FOR SELECT USING (business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid()));

CREATE POLICY "Admins manage test questions" ON public.test_questions FOR ALL USING (
    test_id IN (SELECT id FROM public.tests WHERE business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid()))
);
CREATE POLICY "Students view test questions" ON public.test_questions FOR SELECT USING (
    test_id IN (SELECT id FROM public.tests WHERE business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid()))
);

CREATE POLICY "Admins view submissions" ON public.test_submissions FOR SELECT USING (
    test_id IN (SELECT id FROM public.tests WHERE business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid()))
);
CREATE POLICY "Students insert submissions" ON public.test_submissions FOR INSERT WITH CHECK (
    student_id IN (SELECT id FROM public.students WHERE user_id = auth.uid())
);
CREATE POLICY "Students view own submissions" ON public.test_submissions FOR SELECT USING (
    student_id IN (SELECT id FROM public.students WHERE user_id = auth.uid())
);

-- Alerts
CREATE POLICY "Admins manage alerts" ON public.alerts FOR ALL USING (business_id IN (SELECT id FROM public.businesses WHERE admin_id = auth.uid()));
CREATE POLICY "Students view alerts" ON public.alerts FOR SELECT USING (business_id IN (SELECT business_id FROM public.profiles WHERE id = auth.uid()));

-- 4. HANDLE NEW USER TRIGGER
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  existing_student_id UUID;
  user_role TEXT;
BEGIN
  user_role := new.raw_user_meta_data->>'role';

  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', 'Student User'),
    new.email,
    user_role
  )
  ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name,
      email = EXCLUDED.email,
      role = COALESCE(profiles.role, EXCLUDED.role);

  IF user_role IS NULL OR user_role = 'student' THEN
    SELECT id INTO existing_student_id FROM public.students WHERE email = new.email LIMIT 1;
    IF existing_student_id IS NOT NULL THEN
      UPDATE public.students SET user_id = new.id WHERE id = existing_student_id;
      UPDATE public.profiles SET role = 'student' WHERE id = new.id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
