-- SQL Script to handle Account Deletion Requests and fix Google Sign-Up Role Selection

-- ===================================================
-- 0. ADD MISSING COLUMNS TO TABLES
-- ===================================================
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS blood_group TEXT;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS duration TEXT DEFAULT '1 Year';
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS batch_timing TEXT DEFAULT '10:00 AM - 01:00 PM';

-- Add verified column to profiles table (default to TRUE, will be FALSE for unverified admins)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT TRUE;

-- ===================================================
-- 1. FIX PROFILES TABLE DEFAULT ROLE
-- ===================================================

-- Drop default value for role in profiles so it can be NULL for new social logins
ALTER TABLE public.profiles ALTER COLUMN role DROP DEFAULT;

-- Update the handle_new_user trigger function to NOT set a default role of 'student'
-- if no role was provided in the raw user metadata. This ensures social signups (Google)
-- have a NULL role initially and get routed to /role-select.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  existing_student_id UUID;
  user_role TEXT;
BEGIN
  -- Retrieve role from metadata; do NOT default to 'student' automatically
  user_role := new.raw_user_meta_data->>'role';

  -- Insert profile
  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', 'Student User'),
    new.email,
    user_role
  )
  ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name,
      email = EXCLUDED.email,
      role = COALESCE(profiles.role, EXCLUDED.role);

  -- Link auth account to existing student record if admin added them previously by email
  -- (If role is NULL, we can also try to link it if we assume they might be a student)
  IF user_role IS NULL OR user_role = 'student' THEN
    SELECT id INTO existing_student_id FROM public.students WHERE email = new.email LIMIT 1;
    
    IF existing_student_id IS NOT NULL THEN
      UPDATE public.students
      SET user_id = new.id
      WHERE id = existing_student_id;
      
      -- Since they matched an existing student record, auto-assign 'student' role
      UPDATE public.profiles
      SET role = 'student'
      WHERE id = new.id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ===================================================
-- 2. CREATE ACCOUNT DELETION REQUESTS TABLE
-- ===================================================

CREATE TABLE IF NOT EXISTS public.account_deletion_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  user_name TEXT NOT NULL,
  user_email TEXT NOT NULL,
  requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'recovered', 'rejected')),
  scheduled_delete_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.account_deletion_requests ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Allow users to manage own deletion request" ON public.account_deletion_requests;
DROP POLICY IF EXISTS "Allow admin to manage deletion requests" ON public.account_deletion_requests;

-- Allow authenticated users to insert, read, and update their own deletion requests
CREATE POLICY "Allow users to manage own deletion request" ON public.account_deletion_requests
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Allow admins to perform all operations on deletion requests
CREATE POLICY "Allow admin to manage deletion requests" ON public.account_deletion_requests
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );
