-- PrestoID Database Schema Additions
-- This file contains the schemas missing from the original structure to support the full 11-page specification.

-- 1. MODIFICATIONS TO STUDENTS TABLE
ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS aadhaar_number TEXT, -- Used as a backup claim method, encrypted in application/pgcrypto
  ADD COLUMN IF NOT EXISTS whatsapp_number TEXT,
  ADD COLUMN IF NOT EXISTS secret_code TEXT,
  ADD COLUMN IF NOT EXISTS device_id TEXT, -- For single-device login enforcement
  ADD COLUMN IF NOT EXISTS is_claimed BOOLEAN DEFAULT false;

-- 2. ALERTS / NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT CHECK (type IN ('fee', 'attendance', 'community', 'test_schedule', 'claim_approval')),
  is_read BOOLEAN DEFAULT false,
  requires_action BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to read own alerts" ON public.alerts FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Allow admin to manage alerts" ON public.alerts FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 3. AI TEST ENGINE: TESTS
CREATE TABLE IF NOT EXISTS public.tests (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  batch_name TEXT NOT NULL,
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  duration_minutes INT NOT NULL,
  scheduled_start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read of tests" ON public.tests FOR SELECT USING (true);
CREATE POLICY "Allow admin to manage tests" ON public.tests FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 4. AI TEST ENGINE: QUESTIONS
CREATE TABLE IF NOT EXISTS public.test_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id UUID REFERENCES public.tests(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option TEXT CHECK (correct_option IN ('A', 'B', 'C', 'D')),
  explanation TEXT,
  chapter_tag TEXT
);

ALTER TABLE public.test_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read of test questions" ON public.test_questions FOR SELECT USING (true);
CREATE POLICY "Allow admin to manage questions" ON public.test_questions FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 5. AI TEST ENGINE: RESULTS & ANALYTICS
CREATE TABLE IF NOT EXISTS public.test_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id UUID REFERENCES public.tests(id) ON DELETE CASCADE,
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
  score NUMERIC NOT NULL,
  chapter_wise_analytics JSONB, -- Stores weak/strong areas e.g. {"Indus Valley": 40, "Mahajanapadas": 85}
  exit_count INT DEFAULT 0,
  total_time_away_seconds INT DEFAULT 0,
  exit_type_logs JSONB DEFAULT '[]'::jsonb, -- Array of {type: 'app_switched' | 'connection_lost', time: timestamp}
  is_pending_sync BOOLEAN DEFAULT false,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(test_id, student_id)
);

ALTER TABLE public.test_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to read own test results" ON public.test_results FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Allow admin to view all test results" ON public.test_results FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Allow users to insert own test results" ON public.test_results FOR INSERT WITH CHECK (auth.uid() = student_id);
