/**
 * MockS Exam Category Master Config
 * Covers: Government, Engineering, Medical, Boards, Central Entrance & sub-exams
 */

const EXAM_CONFIGS = [
  // ─────────────────────────────────────────────
  // GOVERNMENT / CIVIL SERVICES
  // ─────────────────────────────────────────────
  {
    id: 'mppsc_pre',
    exam_category: 'MPPSC',
    title_prefix: 'MPPSC Pre General Studies',
    subject_name: 'General Studies',
    language: 'bilingual',
    duration_minutes: 20,
    total_marks: 40,
    questions_per_test: 20,
    marks_per_question: 2,
    negative_marks: 0,
    difficulty_level: 'Medium',
    topics: [
      'Indian Polity & Constitution', 'MP History & Culture', 'MP Geography',
      'Indian History (Ancient, Medieval, Modern)', 'Indian Geography',
      'Indian Economy & Five Year Plans', 'Science & Technology',
      'Environment & Ecology', 'Current Affairs', 'MP Economy & Agriculture',
      'MP Government Schemes', 'Awards & Honours', 'International Relations',
    ],
  },
  {
    id: 'mppsc_mains',
    exam_category: 'MPPSC',
    title_prefix: 'MPPSC Mains General Studies Paper',
    subject_name: 'General Studies (Mains)',
    language: 'bilingual',
    duration_minutes: 30,
    total_marks: 60,
    questions_per_test: 20,
    marks_per_question: 3,
    negative_marks: 0,
    difficulty_level: 'Hard',
    topics: [
      'MP Polity & Administration', 'Indian Polity (Advanced)', 'Social Issues',
      'Ethics & Integrity', 'MP Economy (Detailed)', 'Disaster Management',
      'Science & Technology (Applied)', 'MP Culture & Literature', 'Environmental Law',
    ],
  },
  {
    id: 'mp_police',
    exam_category: 'MP Police',
    title_prefix: 'MP Police Constable / Sub-Inspector Official PYQ',
    subject_name: 'General Studies & Reasoning',
    language: 'bilingual',
    duration_minutes: 20,
    total_marks: 20,
    questions_per_test: 20,
    marks_per_question: 1,
    negative_marks: 0,
    difficulty_level: 'Easy',
    topics: [
      'MP GK & Current Affairs', 'Indian Polity', 'General Science',
      'Logical Reasoning', 'Quantitative Aptitude', 'Hindi Language',
      'Computer Basics', 'Sports & Awards',
    ],
  },
  {
    id: 'mp_patwari',
    exam_category: 'MP Patwari',
    title_prefix: 'MP Patwari Exam Official PYQ',
    subject_name: 'General Knowledge & Rural Development',
    language: 'bilingual',
    duration_minutes: 120,
    total_marks: 100,
    questions_per_test: 20,
    marks_per_question: 1,
    negative_marks: 0,
    difficulty_level: 'Easy',
    topics: [
      'MP Land Records & Revenue Laws', 'MP Agriculture', 'MP GK',
      'General Science', 'Mathematics (Basic)', 'Hindi', 'Computer Basics',
      'Panchayati Raj', 'Rural Development Schemes',
    ],
  },
  {
    id: 'mpsi',
    exam_category: 'MP Sub-Inspector',
    title_prefix: 'MPSI (Sub-Inspector) Official PYQ',
    subject_name: 'General Studies & Aptitude',
    language: 'bilingual',
    duration_minutes: 120,
    total_marks: 200,
    questions_per_test: 20,
    marks_per_question: 2,
    negative_marks: 0.5,
    difficulty_level: 'Medium',
    topics: [
      'Indian Law & Criminal Justice', 'MP GK & Culture', 'Indian Polity',
      'Logical Reasoning', 'General Science', 'Current Affairs', 'Hindi',
    ],
  },

  // ─────────────────────────────────────────────
  // ENGINEERING
  // ─────────────────────────────────────────────
  {
    id: 'jee_main_physics',
    exam_category: 'JEE Main',
    title_prefix: 'JEE Main Physics Official PYQ',
    subject_name: 'Physics',
    language: 'english',
    duration_minutes: 60,
    total_marks: 80,
    questions_per_test: 20,
    marks_per_question: 4,
    negative_marks: 1,
    difficulty_level: 'Hard',
    topics: [
      'Mechanics (Kinematics, Laws of Motion, Work-Energy)', 'Rotational Motion',
      'Gravitation', 'Fluid Mechanics', 'Thermal Physics & Thermodynamics',
      'Waves & Oscillations', 'Electrostatics & Capacitors', 'Current Electricity',
      'Magnetic Effects of Current', 'Electromagnetic Induction', 'Optics (Ray & Wave)',
      'Modern Physics (Photoelectric, Nuclear)', 'Semiconductor Devices',
    ],
  },
  {
    id: 'jee_main_chemistry',
    exam_category: 'JEE Main',
    title_prefix: 'JEE Main Chemistry Official PYQ',
    subject_name: 'Chemistry',
    language: 'english',
    duration_minutes: 60,
    total_marks: 80,
    questions_per_test: 20,
    marks_per_question: 4,
    negative_marks: 1,
    difficulty_level: 'Hard',
    topics: [
      'Mole Concept & Stoichiometry', 'Atomic Structure', 'Chemical Bonding',
      'States of Matter', 'Thermodynamics (Chemical)', 'Equilibrium',
      'Redox & Electrochemistry', 'Chemical Kinetics', 'Surface Chemistry',
      'p-Block Elements', 'd & f Block Elements', 'Organic Chemistry (IUPAC, Reactions)',
      'Biomolecules & Polymers',
    ],
  },
  {
    id: 'jee_main_maths',
    exam_category: 'JEE Main',
    title_prefix: 'JEE Main Mathematics Official PYQ',
    subject_name: 'Mathematics',
    language: 'english',
    duration_minutes: 60,
    total_marks: 80,
    questions_per_test: 20,
    marks_per_question: 4,
    negative_marks: 1,
    difficulty_level: 'Hard',
    topics: [
      'Sets, Relations & Functions', 'Complex Numbers', 'Quadratic Equations',
      'Sequences & Series', 'Binomial Theorem', 'Permutation & Combination',
      'Matrices & Determinants', 'Limits, Continuity & Differentiability',
      'Application of Derivatives', 'Integration (Definite & Indefinite)',
      'Differential Equations', 'Coordinate Geometry', 'Vector & 3D Geometry',
      'Probability & Statistics', 'Trigonometry',
    ],
  },
  {
    id: 'gate_cse',
    exam_category: 'GATE',
    title_prefix: 'GATE CSE (Computer Science) Official PYQ',
    subject_name: 'Computer Science & Engineering',
    language: 'english',
    duration_minutes: 180,
    total_marks: 100,
    questions_per_test: 20,
    marks_per_question: 2,
    negative_marks: 0.67,
    difficulty_level: 'Hard',
    topics: [
      'Data Structures & Algorithms', 'Operating Systems', 'Computer Networks',
      'Database Management Systems', 'Computer Organization & Architecture',
      'Theory of Computation', 'Compiler Design', 'Digital Logic',
      'Discrete Mathematics', 'Engineering Mathematics',
    ],
  },

  // ─────────────────────────────────────────────
  // MEDICAL
  // ─────────────────────────────────────────────
  {
    id: 'neet_biology',
    exam_category: 'NEET UG',
    title_prefix: 'NEET UG Biology Official PYQ',
    subject_name: 'Biology (Botany + Zoology)',
    language: 'english',
    duration_minutes: 60,
    total_marks: 180,
    questions_per_test: 20,
    marks_per_question: 4,
    negative_marks: 1,
    difficulty_level: 'Hard',
    topics: [
      'Cell: The Unit of Life', 'Cell Division (Mitosis, Meiosis)',
      'Biomolecules', 'Photosynthesis & Respiration', 'Plant Growth & Development',
      'Human Physiology (Digestion, Circulation, Excretion)', 'Reproduction',
      'Genetics & Evolution', 'Ecology & Environment', 'Biotechnology',
      'Microbes in Human Welfare', 'Human Health & Disease',
    ],
  },
  {
    id: 'neet_physics',
    exam_category: 'NEET UG',
    title_prefix: 'NEET UG Physics Official PYQ',
    subject_name: 'Physics',
    language: 'english',
    duration_minutes: 45,
    total_marks: 90,
    questions_per_test: 20,
    marks_per_question: 4,
    negative_marks: 1,
    difficulty_level: 'Medium',
    topics: [
      'Mechanics', 'Thermodynamics', 'Waves & Oscillations',
      'Electrostatics', 'Current Electricity & Magnetic Effect',
      'Optics', 'Modern Physics & Semiconductor',
    ],
  },
  {
    id: 'neet_chemistry',
    exam_category: 'NEET UG',
    title_prefix: 'NEET UG Chemistry Official PYQ',
    subject_name: 'Chemistry',
    language: 'english',
    duration_minutes: 45,
    total_marks: 90,
    questions_per_test: 20,
    marks_per_question: 4,
    negative_marks: 1,
    difficulty_level: 'Medium',
    topics: [
      'Basic Concepts & Mole', 'Atomic Structure', 'Chemical Bonding',
      'Thermodynamics', 'Equilibrium', 'Redox & Electrochemistry',
      'Organic Chemistry Fundamentals', 'Biomolecules',
    ],
  },

  // ─────────────────────────────────────────────
  // BOARDS
  // ─────────────────────────────────────────────
  {
    id: 'mp_board_10_science',
    exam_category: 'MP Board',
    title_prefix: 'MP Board Class 10 Science Official PYQ',
    subject_name: 'Science (Class 10)',
    language: 'bilingual',
    duration_minutes: 180,
    total_marks: 100,
    questions_per_test: 20,
    marks_per_question: 1,
    negative_marks: 0,
    difficulty_level: 'Easy',
    topics: [
      'Chemical Reactions & Equations', 'Acids Bases Salts', 'Metals & Non-Metals',
      'Carbon & Its Compounds', 'Life Processes', 'Heredity & Evolution',
      'Light (Reflection & Refraction)', 'Electricity', 'Magnetic Effects',
      'Natural Resources & Environment',
    ],
  },
  {
    id: 'mp_board_12_physics',
    exam_category: 'MP Board',
    title_prefix: 'MP Board Class 12 Physics Official PYQ',
    subject_name: 'Physics (Class 12)',
    language: 'bilingual',
    duration_minutes: 180,
    total_marks: 100,
    questions_per_test: 20,
    marks_per_question: 1,
    negative_marks: 0,
    difficulty_level: 'Medium',
    topics: [
      'Electrostatics', 'Current Electricity', 'Magnetic Effect of Current',
      'Electromagnetic Induction', 'Alternating Current', 'Optics',
      'Dual Nature of Radiation', 'Atoms & Nuclei', 'Semiconductor Devices',
    ],
  },
  {
    id: 'mp_board_12_biology',
    exam_category: 'MP Board',
    title_prefix: 'MP Board Class 12 Biology Official PYQ',
    subject_name: 'Biology (Class 12)',
    language: 'bilingual',
    duration_minutes: 180,
    total_marks: 100,
    questions_per_test: 20,
    marks_per_question: 1,
    negative_marks: 0,
    difficulty_level: 'Medium',
    topics: [
      'Reproduction in Organisms', 'Human Reproduction', 'Reproductive Health',
      'Genetics (Mendelian & Molecular)', 'Evolution', 'Human Health & Disease',
      'Biotechnology & Its Applications', 'Ecology',
    ],
  },

  // ─────────────────────────────────────────────
  // CENTRAL ENTRANCE / COMPETITIVE
  // ─────────────────────────────────────────────
  {
    id: 'ssc_cgl',
    exam_category: 'SSC CGL',
    title_prefix: 'SSC CGL Tier-I Official PYQ',
    subject_name: 'General Awareness & Aptitude',
    language: 'bilingual',
    duration_minutes: 60,
    total_marks: 200,
    questions_per_test: 20,
    marks_per_question: 2,
    negative_marks: 0.5,
    difficulty_level: 'Medium',
    topics: [
      'General Knowledge & Current Affairs', 'Indian History', 'Indian Polity',
      'Indian Geography', 'Indian Economy', 'General Science',
      'Quantitative Aptitude', 'English Language', 'Logical Reasoning',
    ],
  },
  {
    id: 'ssc_chsl',
    exam_category: 'SSC CHSL',
    title_prefix: 'SSC CHSL Tier-I Official PYQ',
    subject_name: 'General Intelligence & English',
    language: 'bilingual',
    duration_minutes: 60,
    total_marks: 200,
    questions_per_test: 20,
    marks_per_question: 2,
    negative_marks: 0.5,
    difficulty_level: 'Easy',
    topics: [
      'General Awareness', 'English Language & Comprehension',
      'Quantitative Aptitude (Basic)', 'Logical Reasoning & Puzzles',
      'Computer Knowledge',
    ],
  },
  {
    id: 'railway_ntpc',
    exam_category: 'Railway',
    title_prefix: 'RRB NTPC CBT-1 Official PYQ',
    subject_name: 'General Awareness, Maths & Reasoning',
    language: 'bilingual',
    duration_minutes: 90,
    total_marks: 100,
    questions_per_test: 20,
    marks_per_question: 1,
    negative_marks: 0.33,
    difficulty_level: 'Medium',
    topics: [
      'Current Affairs & General Awareness', 'Indian History & Culture',
      'Indian Polity & Economy', 'Science & Technology',
      'Quantitative Aptitude', 'Logical Reasoning', 'Computer & IT Basics',
    ],
  },
  {
    id: 'railway_group_d',
    exam_category: 'Railway',
    title_prefix: 'RRB Group D Official PYQ',
    subject_name: 'General Science & Maths',
    language: 'bilingual',
    duration_minutes: 90,
    total_marks: 100,
    questions_per_test: 20,
    marks_per_question: 1,
    negative_marks: 0.33,
    difficulty_level: 'Easy',
    topics: [
      'General Science (Physics, Chemistry, Biology)', 'General Awareness',
      'Mathematics (Basic Arithmetic)', 'Logical Reasoning & Puzzles',
    ],
  },
  {
    id: 'ibps_po',
    exam_category: 'Banking',
    title_prefix: 'IBPS PO Prelims Official PYQ',
    subject_name: 'Reasoning & Quantitative Aptitude',
    language: 'english',
    duration_minutes: 60,
    total_marks: 100,
    questions_per_test: 20,
    marks_per_question: 1,
    negative_marks: 0.25,
    difficulty_level: 'Medium',
    topics: [
      'Logical Reasoning (Syllogism, Coding)', 'Data Interpretation',
      'Number Series & Puzzles', 'English (Reading Comprehension, Error)',
      'Quantitative Aptitude (DI, Arithmetic)', 'Banking Awareness',
    ],
  },
];

module.exports = { EXAM_CONFIGS };
